### ISSUE TITLE
Criar página de mídias

### ISSUE THREAD

**Issue by alinelima1** [alinelima1/bootstrap-dh#5]
você pode personalizar do seu jeito, mas deve ter pelo menos 1 video e 6 imagens de acordo com o seu tema escolhido

- [x] Incluir vídeo em destaque na página
- [x] Fotos de clientes
- [x] Depoimentos dos clientes

**Comment by ggwadera** [comment]
Montei um layout básico com o vídeo e 6 fotos. Deixei o depoimento como lorem ipsum mesmo ainda porque não sei o que fazer por enquanto.

O grid de depoimentos já está responsivo, mostrando em 2 colunas para telas maiores e em 1 coluna para telas menores.
